### ISSUE TITLE
Error during build of "Unsupported Erlang version." with OTP 21.1.1

### ISSUE THREAD

**Issue by OvermindDL1** [hansihe/html5ever_elixir#11]
Tried forcing Rustler to 0.18 to no avail, same error.

**Comment by OvermindDL1** [comment]
Manually updating the Cargo.toml to rustler version 0.18 for both of its entries does make it compile (though with a lot of warnings, none of which look to have anything to do with rustler).  Also noticed that the html5ever crate is *extremely* out of date, it looks like some updating in general is needed?

**Comment by RaphSfeir** [comment]
Any update on this? 
The manual update does fix the error but it is tedious to do it everytime, and in environnements using the Hex published version, (like CI / CD VMs) is a blocking issue.
 
Maybe one of the pull requests updating rustler to 0.18 would solve this?

**Comment by hansihe** [comment]
I'll try to get a new version of this crate released tomorrow

**Comment by OvermindDL1** [comment]
And do note, 21.2 was released yesterday as well.  :-)

**Comment by hansihe** [comment]
Seems I have some work to do tomorrow then :)

**Comment by hansihe** [comment]
New version `0.7.0` published!
