### ISSUE TITLE
Segfaults on highly nested html

### ISSUE THREAD

**Issue by rinpatch** [hansihe/html5ever_elixir#15]
Example:
```
iex(4)> Enum.reduce(1..4000, "", fn _,acc -> "<div>" <> acc end) |> Html5ever.parse()
Segmentation fault
```

While I doubt any HTML document really needs 4k nested tags, this could be abused by attackers if the library is used to parse user-generated content.

I am not too familiar with Rust, but I am pretty sure you are hitting recursion depth limit when transforming the parsed tree to erlang terms.

**Comment by hansihe** [comment]
This should hopefully not be an issue with the latest commits. Would you mind testing again?

**Comment by rinpatch** [comment]
Looks like it's fixed now, can't reproduce even with 100k nested `<div>`s.
