### ISSUE TITLE
Large performance differences between using `parse_sync` or `parse_async`

### ISSUE THREAD

**Issue by mischov** [hansihe/html5ever_elixir#4]
When parsing large (314kB) HTML to create a `Meeseeks.Document`, `Html5ever.Native.parse_sync` runs 2x faster than `Html5ever.Native.parse_async` .

Example project: https://github.com/mischov/meeseeks_html5ever_parse

Example output:
```
$ MIX_ENV=prod mix run -e MeeseeksHtml5everParse.run
Running tests...
Parsed with Html5ever async in 17250.7 us
Parsed with Html5ever sync in 18877.3 us

Created Meeseeks Document from tuples in 6883.2 us

Parsed with Meeseeks async in 66956.9 us
Parsed with Meeseeks sync in 33076.9 us
```

Edit: I'm running Erlang/OTP 19.

**Comment by hansihe** [comment]
I just tested it on my machine, I'm getting these results:

```
$ env MIX_ENV=prod mix run -e MeeseeksHtml5everParse.run
Running tests...
Parsed with Html5ever async in 20553.7 us
Parsed with Html5ever sync in 21025.3 us

Created Meeseeks Document from tuples in 9082.3 us

Parsed with Meeseeks async in 49555.2 us
Parsed with Meeseeks sync in 48633.9 us
```

Do you have any idea what might cause this?

**Comment by mischov** [comment]
I have no idea why that behavior would be different on our two machines, but version differences maybe? Doubt it'd be Rust differences but I guess we could have different Erlangs? Or maybe some kind of OS differences?

Any idea why when the two operations take you 20ms and 10ms respectively but combined they take 50ms? Is it somehow down to scheduling or gc?

**Comment by mischov** [comment]
Closing this issue because it seems like whatever is causing the differences between sync and async for me probably isn't related to your code. 

I really want to get rid of that extra 20ms (20ms + 10ms = 50ms???), but  that's not what this issue was about.

Thanks.

**Comment by hansihe** [comment]
Sorry I haven't been able to look at this more, I have had a really busy week. I should have a chance to look at this more next week.

**Comment by mischov** [comment]
I'm fairly certain the extra time is due to gc related to receiving the tuple-tree of html from html5ever_elixir and then converting it into a flat-map.

I spent much more of my weekend than I should have writing a `FlatDom TreeSink` (inspired by yours and the `RcDom`) that converts to a `Meeseeks.Document `directly, and it looks like it shaves a pretty consistent 30%-40% (conservatively) off of my `Meeseeks.parse` time.

**Comment by hansihe** [comment]
If you would be willing make a pull request, I would be happy to accept that upstream.

**Comment by mischov** [comment]
I'll get the code public in a few days at most, but it's tied fairly intimately to Meeseeks and so probably not appropriate to be pulled into html5ever_elixir (though maybe it will be useful for adaptation or inspiration).

I'm not very good with Rust, either, so I'm sure there are numerous problems and inefficiencies.

**Comment by hansihe** [comment]
If you would be interested, I would be happy to do code review/suggest improvements.

**Comment by mischov** [comment]
Here you go. https://github.com/mischov/meeseeks_html5ever
